apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/npm/0.1/npm.yaml
- create-configuration.Task.yaml
- deploy.Task.yaml
- pipeline.yaml
- quayio.Secret.yaml
- git-credentials.Secret.yaml
- quayio.ServiceAccount.yaml
- rbac.yaml
- triggerbinding.yaml
- triggertemplate.yaml
- webhook-receiver.EventListener.yaml
- webhook-role.yaml
- webhook-rolebinding.yaml
- webhook-route.yaml
- webhook-sa.yaml
# - save-configuration.Task.yaml
# - production-repository.ConfigMap.yaml