apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: squad-3-pipeline-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: squad-3-pipeline
        params:
        - name: source-repo
          value: https://github.com/cloud-native-garage-method-cohort/squad-3-final-app.git
        - name: image-repo
          value: quay.io/tomasz_boczek/squad-3-app
        - name: app-name
          value: squad-3-app
        - name: app-namespace
          value: squad-3-final-app
        workspaces:
          - name: pipeline-ws1
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          # - name: gitops-repository
          #   volumeClaimTemplate:
          #     spec:
          #       resources:
          #         requests:
          #           storage: 1Gi
          #       accessModes:
          #       - ReadWriteOnce
          # - name: git-credentials
          #   secret:
          #     secretName: git-credentials
          - name: gitops-repository
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 1Gi
                accessModes:
                - ReadWriteOnce
          - name: git-credentials
            secret:
              secretName: git-credentials